from ..transport.powershell import PowerShellTransport
import os
import json
from typing import Dict, Any

def clone_qatrack_repo(transport: PowerShellTransport, install_path: str, repo_url: str = "https://github.com/qatrackplus/qatrackplus.git") -> Dict[str, Any]:
    """Clones the QATrack+ repository."""
    if transport.file_exists(os.path.join(install_path, "manage.py")):
        return {"status": "Exists", "message": "QATrack+ already exists at this location."}
    
    # Ensure parent directory exists
    parent_dir = os.path.dirname(install_path)
    if not transport.file_exists(parent_dir):
        transport.run(f"New-Item -ItemType Directory -Path '{parent_dir}' -Force")
    
    try:
        transport.run(f"git clone {repo_url} '{install_path}'")
        return {"status": "Success", "message": f"Successfully cloned to {install_path}"}
    except Exception as e:
        return {"status": "Failed", "message": str(e)}

def setup_venv(transport: PowerShellTransport, install_path: str) -> Dict[str, Any]:
    """Creates a virtual environment and installs dependencies."""
    venv_path = os.path.join(install_path, ".venv")
    python_exe = "python" # Assume in path as per Phase 1
    
    try:
        if not transport.file_exists(venv_path):
            transport.run(f"& {python_exe} -m venv '{venv_path}'")
            
        pip_exe = os.path.join(venv_path, "Scripts", "pip.exe")
        requirements_file = os.path.join(install_path, "requirements.txt")
        
        if transport.file_exists(requirements_file):
            transport.run(f"& '{pip_exe}' install -r '{requirements_file}'")
            # Additional packages needed for Windows
            transport.run(f"& '{pip_exe}' install cherrypy pywin32")
            return {"status": "Success", "message": "Virtual environment and dependencies installed."}
        else:
            return {"status": "Failed", "message": "requirements.txt not found."}
    except Exception as e:
        return {"status": "Failed", "message": str(e)}

def configure_qatrack(transport: PowerShellTransport, install_path: str, db_config: Dict[str, Any]) -> Dict[str, Any]:
    """Generates local_settings.py based on database configuration."""
    settings_path = os.path.join(install_path, "qatrack", "local_settings.py")
    
    # Map our config to Django database settings
    db_engine_map = {
        "MSSQL": "sql_server.pyodbc",
        "PostgreSQL": "django.db.backends.postgresql",
        "MySQL": "django.db.backends.mysql",
        "SQLite": "django.db.backends.sqlite3"
    }
    
    engine = db_engine_map.get(db_config.get("db_type"), "django.db.backends.sqlite3")
    
    settings_content = f"""
# Generated by QATrack+ Manager for Windows
DATABASES = {{
    'default': {{
        'ENGINE': '{engine}',
        'NAME': '{db_config.get("db_name")}',
        'USER': '{db_config.get("db_user", "")}',
        'PASSWORD': '{db_config.get("password", "")}',
        'HOST': '{db_config.get("db_server", "localhost")}',
        'PORT': '{db_config.get("db_port", "")}',
    }}
}}

# Security
SECRET_KEY = 'temporary-secret-key-change-me'
DEBUG = True
ALLOWED_HOSTS = ['*']

# Media and Static
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
"""
    
    # We write this via PowerShell to avoid escaping issues
    try:
        # Escape single quotes for PowerShell
        escaped_content = settings_content.replace("'", "''")
        transport.run(f"@'\n{settings_content}\n'@ | Out-File -FilePath '{settings_path}' -Encoding utf8")
        return {"status": "Success", "message": "local_settings.py configured."}
    except Exception as e:
        return {"status": "Failed", "message": str(e)}

def run_django_commands(transport: PowerShellTransport, install_path: str) -> Dict[str, Any]:
    """Runs migrations and collectstatic."""
    python_exe = os.path.join(install_path, ".venv", "Scripts", "python.exe")
    
    try:
        transport.run(f"& '{python_exe}' manage.py migrate --noinput", cwd=install_path)
        transport.run(f"& '{python_exe}' manage.py collectstatic --noinput", cwd=install_path)
        return {"status": "Success", "message": "Database migrations and static file collection complete."}
    except Exception as e:
        return {"status": "Failed", "message": str(e)}
